"""Tables update

Revision ID: 123318fed55c
Revises: f4a38b9d5a8e
Create Date: 2020-12-19 09:13:11.485331

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from app.tickets.enums import TicketPriority

revision = '123318fed55c'
down_revision = 'f4a38b9d5a8e'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'tickets_photos',
        sa.Column('id', postgresql.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_table('streets')
    op.add_column('tickets', sa.Column('link', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('location_lng', sa.Float(), nullable=True))
    op.add_column(
        'tickets',
        sa.Column(
            'priority',
            Enum(TicketPriority, native_enum=False, length=100),
            nullable=True
        ),
    )
    op.alter_column('tickets', 'approx_done_date', existing_type=sa.DATE(), nullable=True)
    op.alter_column('tickets', 'external_id', existing_type=sa.BIGINT(), nullable=True)
    op.alter_column('tickets', 'number', existing_type=sa.TEXT(), nullable=True)
    op.alter_column('tickets', 'work_taken_by', existing_type=sa.TEXT(), nullable=True)
    op.drop_constraint('tickets_city_id_fkey', 'tickets', type_='foreignkey')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('tickets_city_id_fkey', 'tickets', 'cities', ['city_id'], ['id'])
    op.alter_column('tickets', 'work_taken_by', existing_type=sa.TEXT(), nullable=False)
    op.alter_column('tickets', 'number', existing_type=sa.TEXT(), nullable=False)
    op.alter_column('tickets', 'external_id', existing_type=sa.BIGINT(), nullable=False)
    op.alter_column('tickets', 'approx_done_date', existing_type=sa.DATE(), nullable=False)
    op.drop_column('tickets', 'priority')
    op.drop_column('tickets', 'location_lng')
    op.drop_column('tickets', 'location_lat')
    op.drop_column('tickets', 'link')
    op.create_table(
        'streets',
        sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('category', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('district', sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column('document', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('document_date', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('document_title', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('document_number', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('old_category', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('old_name', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='streets_pkey'),
    )
    op.drop_table('tickets_photos')
