"""Add tickets tags

Revision ID: 19ae468b7062
Revises: 4c74b1406753
Create Date: 2020-12-19 12:01:34.169214

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19ae468b7062'
down_revision = '4c74b1406753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_tag',
                    sa.Column('id', postgresql.UUID(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('ticket_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(('ticket_id',), ['tickets.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('tickets', 'source',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'source',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_table('ticket_tag')
    # ### end Alembic commands ###
