"""Update tickets columns

Revision ID: ff33762efa16
Revises: 58619489f248
Create Date: 2020-12-27 19:09:15.008546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff33762efa16'
down_revision = '58619489f248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'city_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('tickets', 'subject_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('tickets', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tickets', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tickets', 'subject_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('tickets', 'city_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
